project:
  type: website
  output-dir: docs

website:
  title: "Preston R. Johnston"
  navbar:
    right: []
  search: false
  favicon: MIT_logo.jpeg
      

format:
  html:
    theme: flatly
    css: styles.css
    toc: false

editor: visual

