---
title: "COPE recap, Fall 2025"
---

*Clemente Sanchez and Preston Johnston*

PhD student life can at times be a lonely affair. As we work on our dissertations, and periodically get feedback from our committees, we often lack a space for open discussion of written works-in-progress among peers, free of the presentation-style structure that characterize seminars and speaker series events. This is the gap we set out to fill by creating the Comparative Politics and Political Economy workshop (COPE), a regular opportunity for graduate students in the department to provide each other comments on manuscripts at varying stages of progress. We wanted to inherit the positive aspects of CPWIP, its predecessor, while also incorporating tools such as dedicated discussants and more effective advertising to make COPE into one of the best venues for receiving peer feedback in the department. And, we are happy to report, the 2025 Fall semester was a success. We had a total of five discussion meetings, each of which was kicked off by a discussant that provided an overview of the paper being discussed. The papers spanned a variety of topics, country contexts, and methodologies, from quantitative evaluations of the evolution of domestic trade institutions, to qualitative assessments of the effects of social policy and the practice of digital authoritarianism. 

We started the semester on September 23rd with a paper by Jared Kalow, a sixth year PhD candidate in the department. Jared’s research interrogates whether commuting changes the political behavior of citizens in the megacities of the global south. In this paper, he examined whether long commutes change citizens' attitudes toward those in power. He presented preliminary results showing that commuters are more likely to turn against the incumbent APC in Nigeria, relying on evidence at both the individual and aggregate levels. The group discussion revolved around the need to disentangle the parts of the theory that relate to political behavior and political attitudes, and how these dimensions relate to each other. In empirical terms, the discussant and participants suggested additional analyses that could be implemented by the author, such as leveraging remote sensed climate data, as well as potential experimental designs.

Our next meeting on October 9th focused on a paper by visiting PhD student Alissa Siara from the European University Institute. The central aim of her paper was to determine the conditions under which social policies lead to cross-domain feedback effects; in other words, when policies in one area lead to changes in political preferences or behavior in another policy area. In particular, the author was interested in examining whether a cash-transfer program in Brazil increased demand for educational quality, considering that one of the requirements for receiving resources was sending children to school. However, Alissa’s analysis found no significant feedback effects, which the paper explained by reference to the fact that  individuals usually have a hard time assessing educational quality and its returns. Throughout this session, participants of the workshop raised theoretical questions around conceptualization, including distinguishing cross-domain policy feedback from other varieties of policy feedback, and the opportunity to craft a more general theory that explains when cross-domain policy feedback effects might materialize. The discussion of the empirics  revolved around the potential use of administrative microdata in order to support the already existing qualitative evidence. We also discussed how intuitions about social policies developed from experience in developed countries may not readily transfer to Global South contexts. 

On October 23rd we then moved on to a paper by Katharin Tai, who presented a portion of her dissertation. The author asks to what degree new informational technologies have allowed autocrats to do away with bureaucratic discretion, and thus consolidate their control over society. Studying the case of China, Katharin argues that the “data work” integral to digital authoritarianism still requires a significant amount of on-the-ground presence by bureaucrats, and in that sense not only do new digital technologies not remove bureaucratic discretion, they might even increase it. The discussion covered the need to better conceptualize the conditions that shape whether data work requires on-the-ground activity by bureaucrats. In empirical terms, discussants and participants raised the point that it was potentially necessary to expand the analysis to include additional cases that exhibited varied features, as that would be a possibly better way of identifying the conditions under which autocrats can replace bureaucrats with algorithms.

After that, Terrence Roh, a third year PhD student in the department, presented a draft of his dissertation prospectus on November 13th. His work argued that fragmentation can be a strategy that states use in peripheries in order to increase their control over marginalized populations, reducing the space for independent collective action. Studying the case of slums in Lima, Peu, Terrence proposed to study community size, an important input in many models studying collective action and contentious politics, as an endogenous variable affected by state strategies, instead of taking it as an exogenous condition. The discussion centered around whether fragmentation was a conscious strategy by state actors or whether this could be a product of unintended consequences. Furthermore, there was a debate around whether fragmentation could instead lead to citizens more strongly identifying with their communities, making collective action more likely. On the methodological side, discussants and presenters helped narrow down possible quantitative  strategies that could be used to measure community fragmentation, as well as ways of testing the implications of the main argument.

Finally, on December 4th Tyler Sagerstrom circulated a side project that he’s working on parallel to his dissertation. The  author attempts to explain the expansion of multinational firms  into countries with lax intellectual property regimes despite the likelihood that their patented technology could be infringed upon. Tyler argues that institutions such as the International Trade Commission (ITC) in the United States can protect these multinationals by sanctioning companies engaged in IP theft, thus preventing stolen IP from entering the US final market. Therefore, an institution that was initially created to protect U.S. domestic industries from unfair foreign competition has instead been repurposed by multinationals to lower their risks of offshoring to weak rule of law countries. A key point in the discussion was the fact that many of the countries that have weak property rights institutions have become important final markets of their own, in which case the ITC cannot help protect the multinationals trying to sell in non-US final markets. Moreover, participants and discussants raised the question of whether it is cheaper for a company to invest in strengthening the ITC or other trade institutions over attempting to buy protection in the manufacturing country. Empirically, the discussion focused on   how to tighten the empirics around the core argument. The group also discussed certain technical details in some of the paper’s empirical strategies, including one that exploited variation in the leniency of administrative law judges in the ITC. 

When we reflect on these sessions, we notice several general insights. On a theoretical level, discussions often revolved around the need to increase generality, both conceptually and in terms of geographic or temporal scope. Discussants and participants often urged the author to expand their view, usually from one focused on whether a certain phenomena happens and why (or why not), to a more general perspective that tries to explain the conditions under which that phenomena emerges. On an empirical level, discussants and participants often suggested new analyses that could be carried out by the author, which could supplement and help convince the reader about the argument being presented. Equally as important, participants pointed out the analyses that were extraneous to the paper, which helped authors identify the pieces of evidence that were key at advancing their core claims.

Throughout the semester we were able to hone in our skills as researchers thanks to the existence of COPE. We are able to identify three areas in which the workshop allowed us to improve our craft. First, the context of a regular meeting allows participants to have a collegial, constructive setting in which they can give each other feedback. The academic career is shaped by giving and receiving comments, and COPE provides a great training ground  for everyone involved. Second, by featuring  research on a multitude of countries and topics, COPE has exposed us to areas of political science that we were not familiar with beforehand. In that sense, the workshop is a microcosm of the broader discipline. And, finally, COPE presents an opportunity for us to keep working on our own research, creating networks of mutual accountability, improving our empirical analysis, and fine-tuning our ability to develop theoretical arguments. For these reasons and more, we are deeply grateful for support from the MIT Center for International Studies, which helps make COPE a reality.


