---
title: "Research"
---

#### Dissertation project

<details>

<summary>**Paying for Climate Change: The Politics of Insurance in a Warming World**</summary>

*Committee: Kathleen Thelen (chair), Devin Caughey, Evan Lieberman, Leah C. Stokes (UC Santa Barbara)*

My dissertation studies the politics of property and disaster insurance in an era of rising climate risk. As insurance markets across advanced democracies buckle under pressures from climate change, potential reform efforts face tradeoffs between the solidaristic and the actuarial functions of insurance. I develop a framework for characterizing insurance-state relations across developed democracies. I then advance a theory linking climate risk incidence to the distributive politics of insurance which helps explain why some jurisdictions pursue actuarial reforms, whereas others socialize climate costs across policyholders. I test this theory with case studies of insurance reforms including the Risk Rating 2.0 reform to the National Flood Insurance Program (NFIP) and the Flood Re program in the UK. I also quantitatively examine reforms to state-level US insurance markets and public insurance schemes. Finally, I explore the interest-group politics of insurer involvement in climate policymaking. Despite potentially existential risks to the property and casualty (P&C) industry, insurers have remained ambivalent or even opposed to decarbonization and have avoided entering coalitions calling for greater climate adaptation policy. I argue that the insurance industry is cross-pressured by both rising physical risk and rising transition risk which threatens firms' extensive holding of fossil fuel assets. At the firm level, I test whether fossil fuel investment holdings and underwriting revenue are associated with greater support for climate denialist politicians. Overall, I argue that rising climate risk is both exacerbating existing political cleavages and creating new ones, including between low-risk and high-risk policyholders, who have orthogonal incentives over the direction of insurance reforms, and between global reinsurers and direct insurers, who differ in their ability to offload localized climate risk.

</details>

#### Working papers

<details>

<summary>**Ethnicity, Regionalism, and Attitudes about Climate Change in Africa** *(with Devin Caughey and Evan Lieberman)*</summary>

African countries have already suffered some of the worst effects of climate change, but attitudes on the continent vary widely on this issue. Motivated by the extensive literature on the central role of ethnicity in African politics, we examine the degree to which dissensus regarding climate change is structured by ethnic divisions. We fit multilevel models of climate-related Afrobarometer survey items in 29 countries, operationalizing ethnic dissensus as the intraclass correlation coefficient of ethnic affiliation. We find substantial ethnic dissensus in many but not all countries. We then consider two classes of explanations for ethnic dissensus: (1) intergroup inequality in resources such as wealth and political power and (2) differences in ethnic groups' geographic distributions. Across a variety of analyses, we find evidence that ethnic dissensus is rooted primarily in geography, specifically groups' concentration in different regions. By contrast, we find little evidence that non-geographic group attributes explain ethnic differences in climate attitudes. Nevertheless, ethnicity's centrality to the politics of many African countries means that ethnic dissensus, whatever its source, may present a potent barrier to collective action on climate change. *(Draft available upon request)*

</details>

<details>

<summary>**The Electoral Effects of Private Sector Positions: Evidence from the US House**</summary>

Does actively holding an outside private sector position benefit the political careers of politicians? I investigate this question in the context of candidates running for the House in the period 2004-2018. I define a private sector position (PSP) as a politician holding an executive, ownership, or director position at a firm while running for office. I acquire data on House members' outside positions and create a new dataset of challenger candidates' outside positions by digitizing their financial disclosure documents. I argue that PSPs may provide electoral resources to politicians, including in the form of campaign finance and politically influenced business decisions. I then estimate whether PSPs are associated with higher election returns and examine how the effect differs across party and incumbency status. I find that PSPs are associated with a significant electoral advantage, with the effect highest for challenger candidates and Republicans. I investigate two potential mechanisms to explain this result: campaign finance and expansionary behavior around election cycles. I find that candidates with PSPs receive more total contributions, contributions from committees, and individual donations. Linking firms declared on candidates' financial disclosures to panel data on firm characteristics, I find some evidence that firms connected to incumbents hire more during election years relative to challenger-connected and unconnected firms. This suggests that incumbent-connected firms engage in behavior analogous to political business cycles. These results contribute to a growing literature showing politicians with corporate connections can advance their political careers by extracting costly favors from firms. *(Draft available upon request)*

</details>

------------------------------------------------------------------------

#### Works in progress

::: works-in-progress
**Ideology and Individual-level Climate Adaptation in Brazil** *(with Clemente T. Sanchez)*

**Company Towns? Labor Market Concentration, Antitrust Opinion, and Political Behavior.** *(with Alejandro Frydman, Joseph Loffredo, and Gabrielle Peloquin-Skulski)*

**Regime Type and Green Growth**
:::
