---
title: "Writing"
---
A mixture of essays and small, for-fun research projects on topics that interest me. 

<details>

<summary>The existence of network effects is insufficient for causal explanation</summary>

# The existence of network effects is insufficient for causal explanation

*Originally published 9/10/2024*

It has become fashionable lately in political science and economics to emphasize the role of social networks in explaining social phenomena. \[examples!\] The insight that “networks matter” is a basic and important one, and certainly coheres with our lived experiences of the world: We hear about new ideas, events, and behaviors from people in our networks—family, friends, coworkers, classmates. We may want to dress a certain way if our friends have started dressing that way, too. We may be more likely to vote for a candidate if we hear our colleagues discussing that candidate at work. But in this short essay, I want to make the simple point that networks themselves are not complete or satisfying causal explanations. As the adage goes, if one’s friends jumped off a cliff, one would (hopefully) have the wisdom to avoid following suit. My argument is that whenever it appears that a network explains some social, political, or economic outcome, there are several assumptions we should interrogate relating to the more fundamental causes of that outcome and the reasons the network is involved with the outcome’s spread or prevalence.

First, we should avoid confusing the way in which the network is a proximal cause for an idea or behavior (in that it spreads, amplifies, or legitimates it) with the original (or distal) cause of that idea or behavior. The network itself logically cannot be the distal cause of the outcome. Absent some originating force like an exogenous shock or social/political/cultural entrepreneur(s), the idea or behavior would not exist to propagate through the network. The idea or behavior must come from somewhere. It is often important (yet overlooked) to ask.

Second, there are also questions one should ask about the propagation of information through the network itself. What social structures, conditions, or individual attributes encourage this propagation? When node A shares information with node B (thereby forming an edge in the network), this relies on the existence of not only some communication channel between them, but a willingness from A to use it. A significant amount of network analysis research in the social sciences has focused heavily on the receipt of information and less on the incentives or conditions under which an individual shares that information. Does sharing that information or behavior provide esteem for the sender, or does the sender hope to change the behavior of the receiver for either selfish or altruistic reasons?

Third, if we observe individuals following behaviors only after their network demonstrated that behavior first, we should ask, why are these individuals susceptible to network influence? That is, what incentives or pressures do receivers have to adopt the behavior? There are many instances where individuals reject the candidate ideas or behaviors proffered by their networks. Agents endowed with reasoning skills, preferences, and experiences frequently assess whether the network’s behavior is rational from their perspective. Therefore, when an individual adopts an idea/behavior of their network, one or more of three things must be true: 1) the idea/behavior is utility-enhancing and preferable to alternatives (i.e., the individual has learned through the network); 2) the individual feels conscious or subconscious social pressure to adopt the idea/behavior, regardless of its merits; or 3) there are explicit coercive sanctions from the network to adopt the idea/behavior. In this context, we typically are less interested in behavior of category (3), which we don’t usually categorize as “network effects” but rather something like repression or private governance.

Fourth, and most fundamentally, why does the network exist at all, and why does it exist among these particular people? Many networks can be opted into (or opted out of). What about these individuals has brought them into the network, or kept them from leaving? We know from a rich literature in political economy and other subdisciplines on collective action that forming organizations is not straightforward. Networks are often (implicitly) contrasted with more formal organizations that involve costly behaviors such as homeowners’ associations, business groups, or social movements, but networks retain some similarities with these organizations. As mentioned above, sending information via networks does involve a cost to the sender (for example, time, breath, or effort, however small), and may also involve a cost to the receiver. It is usually not possible for an individual to opt out of all networks of which they are a member (true recluses are rare indeed), but it is usually possible to opt out of some networks, which individuals often do if the costs are too high. If a friend group has become hostile or exhausting, a person may quietly withdraw. If a family imposes strict traditional norms around religion or marriage, children may move away or disavow once they come of age. The point is this: networks of the sort typically referred to when we invoke “network analysis” in the social sciences require at least some degree of maintenance and consent, and these are themselves outcomes that must be explained. And crucially, the factors that cause an individual to join the network may also cause them to engage in the behavior reflected in the network. In other words, individual attributes are a confounder for both network membership and behavioral adoption. (A simple example is joining a club related to a hobby, and then adopting the behaviors or strategies from other members of the club—which one does precisely because they are interested in the hobby to begin with).

What do we lose when we bypass the four complexities outlined above and skip straight to the part where networks are a proximal cause for a given outcome? My contention is that network effects are often less interesting than 1) the distal cause of the outcome; 2) the use of channels to spread the outcome; 3) the individual assent or propensity to adopt the behavior; and 4) the existence of the network itself. To take an example, consider a recent paper by the economists Cutler and Donahoe, who study why the opioid epidemic has persisted for so long, despite the seeming thermostatic effects that would cause individuals and policymakers to avoid addiction or overdose. They place the blame for the ongoing epidemic squarely at the feet of social network spillovers: when one individual consumes an opioid, they may tell their friends and families about it, and/or share pills either in person or through online platforms such as Facebook. Cutler and Donahoe state in the paper’s abstract that “spillovers explain 84 to 92 percent of opioid deaths from 1990 to 2018 and are the main reason deaths have increased for so long.” Ignoring for now the complexities introduced later in the paper, let’s take the sentence in the abstract at face value. Is it really the case that spillovers themselves are the reason why people die from opioids? No, of course not. Why do some people want to take opioids to begin with, or put another way, what social conditions make them liable to experiment with opioids and vulnerable to addiction? Although individuals may proximally hear about drugs or acquire them from local contacts, this is not a satisfying explanation for why the epidemic started or persists. Going through the four points outlined above as they pertain to this example, I would tentatively argue that all four significantly qualify the blunt statement that “spillovers cause opioid deaths” and in some cases provide a more interesting or fruitful avenue for social investigation than the mere fact of network spread itself. Consider each point in turn: 1) Origin: The creation of OxyContin and Purdue’s false advertising of it as non-addictive; 2) Propagation: The somewhat surprising fact that people are willing and interested in sharing drugs via channels like Facebook; 3) Uptake: The fact that millions of people have pain, either physical or socioemotional, that make them inclined to abuse opioids (i.e., adopt the behavior of the network); 4) Network existence: The fact that there are social networks in opioid-ravaged areas of the United States that share drugs or information about drugs with each other, or that existing social ties become hijacked and converted into narcotic networks

Each of these points warrants explanation, as well as causal weighting (i.e., how relatively important is each in explaining the full picture of network-induced opioid addictions). In my view, spillovers themselves cannot provide a full causal explanation for a social outcome like the opioid epidemic. We need to understand the initial drivers, the incentives for propagation, the conditions for uptake, and the conditions for ongoing network existence and stability. When we incorporate these considerations, it becomes immediately clear that an explanation along the lines of Deaton and Case’s “deaths of despair” is needed (regardless of the truth of their particular argument). At least in the Deaton and Case account there is a plausible claim as to why people may want or need to take opioids, why social networks have been hijacked into being drug-sharing networks, and what policy prescriptions could exist that would address these background/distal causes rather than treating merely the proximal cause of network spillovers.

</details>

<details>

<summary>Do international soccer teams with co-national managers perform better?</summary>

# Do international soccer teams with co-national managers perform better?

*Originally published 9/10/2024*

This past summer, I watched many hours of the Euros and Copa America international soccer tournaments. Most top teams generally have managers (aka coaches) from the same country as the players (Didier Deschamps with France, Gareth Southgate with England), but not all (examples!). This got me wondering---do teams who hire coaches from another country perform better or worse than teams who hire coaches from the same country?

Soccer is a highly international sport, with players coming from virtually every continent. Liverpool FC, for example, my favorite club, regularly fields starting players from Egypt, Uruguay, Colombia, Argentina, the Netherlands, Scotland, France, and England. When players move teams, they're often not just changing allegiances --- they're moving to a new country with a different language and culture. This poses a challenge from a team communication standpoint. Many foreign players take language classes, particularly in English, and some players may avoid media appearances for years, so as to not sound foolish giving an interview in their non-native tongue. 

Contemporary soccer tactics are also fairly complex. Players need to know concepts such as "pressing triggers," the difference between a regular and an "inverted" fullback, the difference between a single and "double pivot," and so on. Managers attempt to stamp their tactical preferences on teams. When Arne Slot replaced Jurgen Klopp at Liverpool, the consensus was that he preferred a slightly--but not excessively--possession-based playstyle that valued quick, short passes and prioritized control in the center of the pitch rather than the wings. Again, not entirely straightforward concepts to explain even to native speakers! The communication challenge of soccer tactics is greatly exacerbated by the strictures of international football, where teams have much less time to train together, and whose rosters are composed of whoever is best in the country at a given position, leading to imbalances where some positions have a dearth of talent, or where some players prefer one playstyle, and other players prefer another. Is it easier to figure out a cohesive playstyle and get a team playing together when the coach is from the same country as the players? What about when the coach is from another country, but still natively speaks the same language? 

surprised that no one has examined this with data 

tested

control for ranks 

1 month before 

24 months before 

conclusion 





</details>
